In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
df = pd.DataFrame(data = data.data,columns=data.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df["target"] = data.target

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [8]:
X = df.drop("target",axis=1)
y = df.target

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [11]:
X_train.shape

(120, 4)

In [12]:
X_test.shape

(30, 4)

In [13]:
from sklearn.svm import SVC

In [14]:
model = SVC()
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(SVC(C=1.0,kernel='rbf',gamma='scale'), X, y, cv = 3)

array([0.96, 0.98, 0.94])

In [17]:
cross_val_score(SVC(C=1.0,kernel='linear'), X, y, cv = 3)

array([1.  , 1.  , 0.98])

In [18]:
cross_val_score(SVC(C=10.0,kernel='rbf'), X, y, cv = 3)

array([0.98, 1.  , 0.94])

In [19]:
# To avoid hyper parameter tune / which is perfect for a score

In [20]:
kval = ["rbf","linear"]
cval = [1,10,20]

In [21]:
for i in kval:
    for j in cval:
        score = cross_val_score(SVC(C = j,kernel=i),X,y,cv = 3)
        print(i,":" ,j,"=",np.average(score))

rbf : 1 = 0.96
rbf : 10 = 0.9733333333333333
rbf : 20 = 0.98
linear : 1 = 0.9933333333333333
linear : 10 = 0.9733333333333333
linear : 20 = 0.9666666666666667


In [22]:
#Grid search cv

In [23]:
from sklearn.model_selection import GridSearchCV

In [24]:
clf = GridSearchCV(SVC(gamma='scale'),{'kernel':['rbf','linear'],'C':[1,10,20]})

In [25]:
clf.fit(X,y)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [26]:
a = clf.cv_results_
a

{'mean_fit_time': array([0.00391898, 0.00288482, 0.00269003, 0.00429454, 0.00420151,
        0.00255408]),
 'std_fit_time': array([0.0033394 , 0.0025331 , 0.00320255, 0.00304532, 0.00222783,
        0.00237702]),
 'mean_score_time': array([0.00186405, 0.0018743 , 0.00182352, 0.00140009, 0.0006474 ,
        0.00181432]),
 'std_score_time': array([0.00311527, 0.00268408, 0.00259766, 0.0020139 , 0.00058807,
        0.00160752]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [27]:
df = pd.DataFrame(a)

In [28]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.003919      0.003339         0.001864        0.003115       1   
1       0.002885      0.002533         0.001874        0.002684       1   
2       0.002690      0.003203         0.001824        0.002598      10   
3       0.004295      0.003045         0.001400        0.002014      10   
4       0.004202      0.002228         0.000647        0.000588      20   
5       0.002554      0.002377         0.001814        0.001608      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.966667           0.966667           0.933333                1.0   
1           1.000000           0.966667           0.966667                1.0   
2           1.000000           0.966667           0.966667                1.0   
3           1.000000           0.900000           0.966667                1.0   
4           1.000000           0.966667           0.966667                1.0   
5           1.000000           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.966667        0.021082                5  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.980000        0.016330                1  
5         0.966667        0.042164                5

In [29]:
df[["params","mean_test_score","rank_test_score"]]

params  mean_test_score  rank_test_score
0      {'C': 1, 'kernel': 'rbf'}         0.966667                5
1   {'C': 1, 'kernel': 'linear'}         0.980000                1
2     {'C': 10, 'kernel': 'rbf'}         0.980000                1
3  {'C': 10, 'kernel': 'linear'}         0.973333                4
4     {'C': 20, 'kernel': 'rbf'}         0.980000                1
5  {'C': 20, 'kernel': 'linear'}         0.966667                5

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
rs = RandomizedSearchCV(SVC(gamma='scale'),{'kernel':['rbf','linear'],'C':[1,10,20]},cv=3,n_iter=3)

In [32]:
rs.fit(X,y)

RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [33]:
rs.cv_results_

{'mean_fit_time': array([0.00387375, 0.0041852 , 0.00299835]),
 'std_fit_time': array([0.00283787, 0.00203202, 0.0028585 ]),
 'mean_score_time': array([0.00253439, 0.00077518, 0.00223382]),
 'std_score_time': array([0.00319667, 0.00075579, 0.00227128]),
 'param_kernel': masked_array(data=['rbf', 'linear', 'linear'],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[20, 20, 1],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 20},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'linear', 'C': 1}],
 'split0_test_score': array([0.98, 1.  , 1.  ]),
 'split1_test_score': array([0.98, 0.94, 1.  ]),
 'split2_test_score': array([0.98, 0.96, 0.98]),
 'mean_test_score': array([0.98      , 0.96666667, 0.99333333]),
 'std_test_score': array([0.        , 0.02494438, 0.00942809]),
 'rank_test_score': array([2, 3, 1])}

In [34]:
df1 = pd.DataFrame(rs.cv_results_)

In [35]:
df1

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.003874      0.002838         0.002534        0.003197          rbf   
1       0.004185      0.002032         0.000775        0.000756       linear   
2       0.002998      0.002859         0.002234        0.002271       linear   

  param_C                         params  split0_test_score  \
0      20     {'kernel': 'rbf', 'C': 20}               0.98   
1      20  {'kernel': 'linear', 'C': 20}               1.00   
2       1   {'kernel': 'linear', 'C': 1}               1.00   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0               0.98               0.98         0.980000        0.000000   
1               0.94               0.96         0.966667        0.024944   
2               1.00               0.98         0.993333        0.009428   

   rank_test_score  
0                2  
1                3  
2                1

In [36]:
df1[["params","mean_test_score","rank_test_score"]]

params  mean_test_score  rank_test_score
0     {'kernel': 'rbf', 'C': 20}         0.980000                2
1  {'kernel': 'linear', 'C': 20}         0.966667                3
2   {'kernel': 'linear', 'C': 1}         0.993333                1