In [ ]:
## import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings("ignore")

In [2]:
digit = load_digits()

In [3]:
digit

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digit.data, digit.target, test_size=0.20, random_state=42)

In [5]:
X_train.shape

(1437, 64)

In [6]:
y_train.shape

(1437,)

In [7]:
X_test.shape

(360, 64)

In [8]:
y_test.shape

(360,)

In [9]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9694444444444444

In [10]:
sv = SVC()
sv.fit(X_train,y_train)
sv.score(X_test,y_test)

0.9861111111111112

In [11]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9722222222222222

In [12]:
# K-fold
# To overcome/reduce the drawback of train_test_split model
# in a train_test_split we can separate the sample in training and testing,that's why it give wrong predicted value.

In [13]:
# ceate a function to reduce maximum steps for if we use multiple algorithm in one DataFrame
def get_score(model,X_train,y_train,X_test,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [14]:
get_score(rf,X_train,y_train,X_test,y_test)

0.9805555555555555

In [15]:
get_score(lr,X_train,y_train,X_test,y_test)

0.9694444444444444

In [16]:
get_score(sv,X_train,y_train,X_test,y_test)

0.9861111111111112

In [17]:
from sklearn.model_selection import KFold

In [18]:
# why we can use KFold
# 1. in a kfold algorithm they can work with all sample in training and testing.
# 2. It work with according to index.
# 3. It work with only input not a output.
# 4. It has need to provide a n_fold, According to n_fold they can split all input sample n times splitting(training,testing).
# 5. It work with all data.
# 6. Here, we find mean/average value manually.

In [19]:
l = [1,2,3,4,5,6,7,8,9]

In [20]:
fold = KFold(n_splits=3)

In [21]:
fold.split(l)

<generator object _BaseKFold.split at 0x00000204835F32E0>

In [22]:
for train_index,test_index in fold.split(l):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
from sklearn.model_selection import StratifiedKFold

In [24]:
kf = StratifiedKFold(n_splits = 3)

In [25]:
l = [1,2,3,4,5,6,7,8,9]
l1 = [0,0,0,1,1,1,2,2,2]

In [26]:
for train_index,test_index in kf.split(l,l1):
    print(train_index,test_index)

[1 2 4 5 7 8] [0 3 6]
[0 2 3 5 6 8] [1 4 7]
[0 1 3 4 6 7] [2 5 8]


In [27]:
for train_index,test_index in kf.split(digit.data,digit.target):
    X_train,X_test =digit.data[train_index],digit.data[test_index]
    y_train,y_test =digit.target[train_index],digit.target[test_index]

In [28]:
X_train.shape

(1198, 64)

In [29]:
X_test.shape

(599, 64)

In [30]:
y_train.shape

(1198,)

In [31]:
y_test.shape

(599,)

In [32]:
get_score(lr,X_train,y_train,X_test,y_test)

0.9165275459098498

In [33]:
get_score(sv,X_train,y_train,X_test,y_test)

0.9649415692821369

In [34]:
get_score(rf,X_train,y_train,X_test,y_test)

0.9298831385642737

In [35]:
lr_score = []
svc_score = []
rf_score = []
for train_index,test_index in kf.split(digit.data,digit.target):
    X_train,X_test = digit.data[train_index],digit.data[test_index]
    y_train,y_test = digit.target[train_index],digit.target[test_index]
    lr_score.append(get_score(lr,X_train,y_train,X_test,y_test))
    svc_score.append(get_score(sv,X_train,y_train,X_test,y_test))
    rf_score.append(get_score(rf,X_train,y_train,X_test,y_test))

In [36]:
lr_score

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [37]:
svc_score

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [38]:
rf_score

[0.9449081803005008, 0.9499165275459098, 0.9315525876460768]

In [39]:
import numpy as np

In [40]:
np.mean(lr_score)

0.9265442404006677

In [41]:
np.mean(rf_score)

0.9421257651641625

In [42]:
np.mean(svc_score)

0.9699499165275459

In [43]:
from sklearn.model_selection import cross_val_score

In [44]:
cross_val_score(LogisticRegression(max_iter=7600),digit.data,digit.target,cv=5)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [45]:
cross_val_score(SVC(),digit.data,digit.target,cv=5)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [46]:
    cross_val_score(RandomForestClassifier(),digit.data,digit.target,cv=5)

array([0.93611111, 0.90555556, 0.95543175, 0.9637883 , 0.92200557])

In [47]:
cross_val_score(SVC(kernel="sigmoid"),digit.data,digit.target,cv=5)

array([0.87777778, 0.84444444, 0.89972145, 0.93314763, 0.84679666])

In [48]:
cross_val_score(SVC(gamma="auto"),digit.data,digit.target,cv=5)

array([0.41111111, 0.45      , 0.454039  , 0.44846797, 0.47910864])